### ISSUE TITLE
Adding wukong to the Gemspec in Rails v3.2.3 Ruby v1.9.3 causes "stack level too deep"

### ISSUE THREAD

**Issue by toddwilson** [infochimps-labs/wukong#13]
Despite trying to get rails to be more verbose, adding wukong to the Gemspec yields this error on starting the rails console:

```
script/rails:6: stack level too deep (SystemStackError)
```

**Comment by nneubauer** [comment]
+1

**Comment by mrflip** [comment]
odd. ill take a look

**Comment by mrflip** [comment]
I haven't debugged the including-in-rails part, but I've just got all the Gemfiles of the wukong suite working across Ruby, JRuby and RBX. In doing so the dependency count has gone much down.

Mind trying a `gem 'wukong', :github => 'infochimps-labs/wukong'` and let me know if you still see the error?

**Comment by nneubauer** [comment]
`bundle update wukong` yields now

```
Using wukong (2.1.0) from git://github.com/infochimps-labs/wukong (at master) 
wukong at /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/bundler/gems/wukong-d656650bdae9 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
["examples/server_logs/breadcrumb_edges.rb", "examples/server_logs/histograms.rb", "examples/server_logs/page_counts.pig", "notes/away/icss/icss_specification.textile", "notes/away/swineherd/swineherd-old-readme.textile", "notes/away/wukong-fs/wukong-fs-old-readme.textile", "notes/away/wukong-transform/wukong-processor-old-readme.textile", "spec/data/a_atsigns_b.tsv", "spec/data/a_follows_b.tsv", "spec/data/tweet.tsv", "spec/data/twitter_user.tsv"] are not files
```

`rails c` yields

```
Loading jruby-openssl in a non-JRuby interpreter
Loading jruby-openssl in a non-JRuby interpreter

/Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/jruby-openssl-0.7.7/lib/shared/openssl.rb:10:in `require': cannot load such file -- jopenssl (LoadError)
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/jruby-openssl-0.7.7/lib/shared/openssl.rb:10:in `<top (required)>'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/thin-1.3.1/lib/thin.rb:6:in `require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/thin-1.3.1/lib/thin.rb:6:in `<top (required)>'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:68:in `require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:66:in `each'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:66:in `block in require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:55:in `each'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler/runtime.rb:55:in `require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.1.0/lib/bundler.rb:118:in `require'
from /Users/nneubauer/Documents/Projektgruppe/rails-app/config/application.rb:7:in `<top (required)>'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/commands.rb:39:in `require'
from /Users/nneubauer/.rvm/gems/ruby-1.9.3-p0/gems/railties-3.2.6/lib/rails/commands.rb:39:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

(Using ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.3.0])

**Comment by mrflip** [comment]
The second was caused by jeweler tracking mud through the gemspec; upgrade configliere to the newest pushed gem (0.4.16)  and it should fix itself.

The first error is harmless; I think a gemspec update I just made fixes it. Thanks for trying this out.

**Comment by nneubauer** [comment]
`bundle update wukong` now does give the same message. `Using wukong (2.1.0)`, propably not getting updated.
`rails c` now shows the same `script/rails:6: stack level too deep (SystemStackError)` the other warning is gone.
