### ISSUE TITLE
stage.rb `handle_extra_attributes': undefined method `merge!' for nil:NilClass 

### ISSUE THREAD

**Issue by lorgio** [infochimps-labs/wukong#25]
I've tried this on master and on the leslie branch. both are coming up with the same error.

I try and run the rspec files and i try to run any example and I get the same error.

i'm running OSX Mavericks with ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]

Either the args are being over-written to nil, or the default is not being set.

``` ruby
/dev/some-project/map_reduce_jobs/wukong/lib/hanuman/stage.rb:78:in `handle_extra_attributes': undefined method `merge!' for nil:NilClass (NoMethodError)
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/gorillib-0.5.2/lib/gorillib/model/base.rb:82:in `receive!'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/gorillib-0.5.2/lib/gorillib/model/base.rb:23:in `initialize'
    from /dev/some-project/map_reduce_jobs/wukong/lib/hanuman/stage.rb:26:in `new'
    from /dev/some-project/map_reduce_jobs/wukong/lib/hanuman/stage.rb:26:in `builder'
    from /dev/some-project/map_reduce_jobs/wukong/lib/hanuman/stage.rb:36:in `register'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong/widget/filters.rb:42:in `<class:Filter>'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong/widget/filters.rb:6:in `<class:Processor>'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong/widget/filters.rb:2:in `<module:Wukong>'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong/widget/filters.rb:1:in `<top (required)>'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong/widgets.rb:1:in `<top (required)>'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong.rb:47:in `require_relative'
    from /dev/some-project/map_reduce_jobs/wukong/lib/wukong.rb:47:in `<top (required)>'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /dev/some-project/map_reduce_jobs/wukong/spec/spec_helper.rb:1:in `<top (required)>'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /dev/some-project/map_reduce_jobs/wukong/spec/examples/dataflow/fibonacci_series_spec.rb:1:in `<top (required)>'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:77:in `rescue in run'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:73:in `run'
    from /.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by ccbcreg** [comment]
Try using rubygems 1.8 instead of 2.

**Comment by lorgio** [comment]
i'll download it now, and try it out @ccbcreg, but has this not been tested on 1.9+? i'd hate to just setup RVMs on a box in order to use this gem..

**Comment by lorgio** [comment]
1.8.7 won't work, since it uses require_relative in [wukong.rb](https://github.com/infochimps-labs/wukong/blob/master/lib/wukong.rb#L6) , which was introduced in 1.9.3?  I'm downloading that now and trying it.

**Comment by lorgio** [comment]
Works on 1.9.3-p545.  Closing now since i have it working. Is there any roadmap to upgrade since the EOL of 1.9 is Feb 23rd 2015?

**Comment by aseever** [comment]
Thanks for the notes - glad to hear you got it working. We're updating our Ruby version support in the next major release, scheduled for Aug 15.

**Comment by lorgio** [comment]
awesome! thanks for the update!

**Comment by mbell697** [comment]
I'm still seeing this error on 4.0.0, any update on ruby 2.0 support?

**Comment by ssimeonov** [comment]
+1 on 2.0 support

**Comment by rjurney** [comment]
This error keeps me from using Wukong on mac os x. :(
