### ISSUE TITLE
undefined method 'param_definitions' for #<Configliere::Param>

### ISSUE THREAD

**Issue by sweetnickyc** [infochimps-labs/wukong#6]
when using wukong from the command line, when I try to specify input and output files, I get this error:

```
/usr/lib/ruby/gems/1.8/gems/configliere-0.4.4/lib/configliere/define.rb:166:in `method_missing': undefined method `param_definitions' for #<Configliere::Param:0xb73c5930> (NoMethodError)
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script.rb:246:in `non_wukong_params'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script.rb:245:in `reject'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script.rb:245:in `non_wukong_params'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script.rb:178:in `mapper_commandline'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script/local_command.rb:28:in `local_commandline'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script/local_command.rb:9:in `execute_local_workflow'
from /usr/lib/ruby/gems/1.8/gems/wukong-2.0.0/lib/wukong/script.rb:149:in `run'
```

The problem seems to be here - apparently newer versions of Configliere use 'definition_of' rather than 'param_definitions'.

```
def non_wukong_params
  options.
    reject{|param, val| options.param_definitions[param][:wukong] }.
    map{|param,val| "--#{param}=#{val}" }.
    join(" ")
end
```

Changing the 'reject' line to "reject{|param, val| options.definition_of(param)[:wukong] }." seems to do the trick.

**Comment by mrflip** [comment]
Thanks @sweetnickyc -- I should also add a note on wukong to be careful about upgrading to configliere 0.4.x.  If you have any more issues, downgrade to 0.3.4.
